name: CI-Build
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

env:
  JAVA_VERSION: '17'
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
      
      - name: Build with Maven
        run: mvn -B package --file pom.xml
          
      - name: Print finished building
        run: echo "The app building finished successfully!"
