name: Build CI

on:
  pull_request:
    branches: ['dev_v4']

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        architecture: x64
        cache: 'maven'

    - name: Build with Maven
      run: mvn clean install

    - name: Finalize Build
      run: echo "Build completed successfully!"
